import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Providers from "@/components/providers";
import { auth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Ai Chat App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-mono',
  display: 'swap',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body
        className={`${spaceMono.className} antialiased flex h-screen`}
        >
          <Providers>
            {session?.user ? (
              <>
                <Sidebar/>
                {children}
              </>
            ) : (
              <div className="flex-1 flex flex-col h-screen items-center justify-center gap-5">
                <h1 className="text-5xl font-bold">Ai Chat App</h1>
                <p className="text-muted-foreground text-center max-w-md">
                  Sign in to start chatting with AI agents that can browse the web and
                  answer your questions in real time.
                </p>
                <Link href="/api/auth/signin">
                  <Button size="lg">Sign in to get started</Button>
                </Link>
              </div>
            )}
          </Providers>
      </body>
    </html>
  );
}
